### ISSUE TITLE
Logging twice when importing winerp with discord.py

### ISSUE THREAD

**Issue by ljouhault** [nouman0103/winerp#17]
```py
import discord
import winerp


class MyClient(discord.Client):
    async def on_message(self, message):
        if message.content == 'raise error':
            raise Exception('test2')


intents = discord.Intents.all()
intents.typing = False
client = MyClient(intents = intents)


client.run(TOKEN)
```

This simple code, when using the `raise error` command, logs the exception twice, but the exact same code, without the second line `import winerp` logs only once. (note that winerp is not used at all here, only imported).

Tried and reproduced on windows and debian, with python 3.9 to 3.11

**Comment by nouman0103** [comment]
did you install winerp using pypi or git?

**Comment by ljouhault** [comment]
Pypi, and I'm up to date

**Comment by nouman0103** [comment]
I have identified the issue. Seems like the dependent module websockets_server uses basicConfig which also enables the logging for discord.py
https://github.com/Pithikos/python-websocket-server/issues/85
