### ISSUE TITLE
on_winerp_request

### ISSUE THREAD

**Issue by ljouhault** [nouman0103/winerp#22]
I was previously using pypi winerp version, and `on_winerp_request` event was being called with parameters route and data.

I recently updated to the last github version and now the same event is being called with no parameters. (registered route are correctly wired as well as their parameters though).

If this is an intended behaviour, how do we get the route and data in `on_winerp_request` now ?

**Comment by ljouhault** [comment]
Nevermind, it was actually one of my own modification on the lib, that's why I lost it when upgrading.

However, it would be cool to add it in the lib actually

**Comment by nouman0103** [comment]
It'll be added in the next pypi version 👍
